### ISSUE TITLE
Content Update Error on Android

### ISSUE THREAD

**Issue by hideharu1977** [blefebvre/aem-phonegap-starter-kit#63]
Content update error is observed on Android emulator 

Replication procedure:
1) Download aem-phonegap-starter-kit-master.zip (downloaded on Nov 6th)
2) Deployed the project on local instance of AEM.  (author: http://localhost:4502, publish: http://localhost:4503) 
3) Ensure that the app can be executed for both iOS and Android emulator
4) Update contents on ShapesCon app (http://localhost:4502/cf#/content/phonegap/ShapesCon/en/home.html)
5) Publish updates via Content Update menu.
- The content update on iOS emulator works without issues.  
- 404 error is observed on Android emulator:
![screen shot 2015-11-10 at 18 58 49](https://cloud.githubusercontent.com/assets/15774931/11059493/6bfd3ff6-87dd-11e5-8c1a-e1ba611f7acc.png)

- The request URL returns following, so exepcted behavior is for content update to work on Android as well. 
<img width="763" alt="screen shot 2015-11-10 at 19 05 36" src="https://cloud.githubusercontent.com/assets/15774931/11059664/551f11d2-87de-11e5-95f2-4f084718fe12.png">

**Comment by blefebvre** [comment]
@hideharu1977, thank you for the detailed report.

`localhost` has a different meaning on Android, unfortunately (see [0] for details). As a workaround you can use either `10.0.2.2` (which will fail on iOS), or the IP address of your machine. 

![screen shot 2015-11-10 at 4 51 44 pm](https://cloud.githubusercontent.com/assets/1048207/11076768/9375b7ce-87ca-11e5-81ca-2a94ec81d568.png)

[0] http://developer.android.com/tools/devices/emulator.html#networkaddresses

**Comment by blefebvre** [comment]
I added a note to the README: https://github.com/blefebvre/aem-phonegap-starter-kit#a-note-on-localhost

**Comment by hideharu1977** [comment]
@blefebvre,
Awesome.  Thank you for the update!

**Comment by MTamPham** [comment]
Hi @blefebvre  and @hideharu1977,

I understand that the solution in this case is use either 10.0.2.2 or the IP address instead of localhost, but could you please show me in detail how I can change it?
I tried to copy angular-app-module.js.jsp in /libs/mobileapps/components/angular/ng-page to ng-ionic-page and modify $scope.publishServer but it does not work.

Thank you in advance.

**Comment by MTamPham** [comment]
Thank you both of you, guys. I found the solution by myself and I'm pleasure to share it for someone who have the same issue with me
1. Copy **content-sync-2** folder under **/etc/clientlibs/mobile** in CRXDE Lite and copy it in anywhere you like (in my case, I put it to /etc/clientlibs/Demo, because I changed _brand_name_placeholder_ to _Demo_ and _app_name_holder_ to _MyFirstAEMMobileApp_), then you need to modify **categories** property to your desired name (for example: _my.custom.content-sync-2_).
2. Create a JS file which named globalVariable in order to defined an IP address to update content, the IP address is either 10.0.2.2 or the IP address of your machine as @blefebvre mentioned above.
3. Open js.txt file and modify it as below
```
#base=js
globalVariable.js
init.js
contentUtils.js
contentInit.js
contentUpdate.js
```
4. Open contentUpdate.js, then updating in **isContentPackageUpdateAvailable** function
```
if (contentPackageDetails) {
        	// Replace 'localhost' to the IP address on your machine to fix Update Hanlder issue on Android
        	if(contentPackageDetails.serverURL.indexOf("localhost") >= 0) {
        		contentPackageDetails.serverURL = contentPackageDetails.serverURL.replace("localhost", ipAddress);
        	}
...
}
```
and insert these lines before
```
var updateServerURI = getServerURL(contentPackageDetails);
``` 
in **updateContentPackageByName** function
```
// Replace 'localhost' to the IP address on your machine to fix Update Hanlder issue on Android
        	if(contentPackageDetails.serverURL.indexOf("localhost") >= 0) {
        		contentPackageDetails.serverURL = contentPackageDetails.serverURL.replace("localhost", ipAddress);
        	}
```
to make sure Update URL is your desired IP address instead of 'localhost'
5. In **/etc/clientlibs/Demo/utility**, modify **dependencies** property from _cq.mobile.content-sync-2_ to _my.custom.content-sync-2_

Last but not least, remember to modify the last value in **embed** property under **/etc/designs/phonegap/Demo/_MyFirstAEMMobileApp_/clientlibsall** from _cq.mobile.content-sync-2_ to _my.custom.content-sync-2_

I hope it help.
